on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build
        working-directory: ./typst-math-rust
        
      - name: Install npm dependencies 
        run: npm i
      - name: Package extension
        run: npm run package -o typst-math.vsix
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: typst-math.vsix
          path: typst-math.vsix


  release:
    runs-on: ubuntu-latest
    needs: [build, build_alpine]
    if: success() && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts


  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4

      - name: Deploy to VS Code Marketplace
        run: npx vsce publish --packagePath $(find . -type f -iname '*.vsix')
        env:
          VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}

      - name: Deploy to OpenVSX
        run: npx ovsx publish --packagePath $(find . -type f -iname '*.vsix')
        env:
          OVSX_PAT: ${{ secrets.OPENVSX_ACCESS_TOKEN }}
